#!/bin/bash
#	twitch credentials
    HOST=live.twitch.tv/app/
    KEY=`cat .twitchkey` #twitchkey is a hidden text file with your streamkey 
    
avconv  -f video4linux2 -pix_fmt yuv422p -i /dev/video0 \ 
-r 30 -bufsize 1000k -b 4000k  -filter scale=iw/3:ih/3 \ 
-c:v libx264 -preset superfast \ 
-f flv rtmp://$HOST/$KEY #rtpm protocol
exit 0
#/dev/video0 is the default v4l2 webcam ,choose correct device number
#mandatory video codec for twitch is h264 or libx264 equivalent
