#!/bin/bash
##twitch credentials#
    HOST=live-mrs.twitch.tv/app
    KEY=`cat .twitchkey` #twitchkey is a hidden text file with your streamkey
#stream specs#
FPS="60"
BUFF="6M"
OUTRES="1280x720"
CODEC="h264_omx"
PIX="yuv420p"
#video input  1280x720 yuvj422p
ffmpeg -f video4linux2 -framerate $FPS -i /dev/video0 \
-force_key_frames:0 00:00:02 \
-bufsize $BUFF -b:v $BUFF -minrate $BUFF -maxrate $BUFF \
-c:a aac -b:a 128k -ac 2 -ar 44100 \
-c:v $CODEC -pix_fmt $PIX -s $OUTRES -g 30  \
-f flv rtmp://$HOST/$KEY #rtpm protocol
exit 0
# video output 768x576 1280x720
#/dev/video0 is the default v4l2 webcam ,chose correct device number
#mandatory video codec for twitch is h264 or libx264 equivalent
# codecs libx264 h264_vaapi h264_v4l2m2m h264_omx(32 bit OS) issues other codecs won't be decoded under android
#bitrate 4M#
