#!/bin/bash
##youtube credentials#
    HOST=a.rtmp.youtube.com/live2
    KEY=`cat .youtubekey` #twitchkey is a hidden text file with your streamkey
#stream specs#
FPS="60"
BUFFER="3M"
BUFF="2M"
OUTRES="854x480"
CODEC="h264_omx"
PIX="yuv420p"
THREAD="16"
#video input  1280x720 yuvj422p
ffmpeg -f alsa -thread_queue_size $THREAD -i default -f video4linux2 -thread_queue_size $THREAD -framerate $FPS -i /dev/video0 -force_key_frames:0 00:00:02 \
-c:v $CODEC -pix_fmt $PIX -r $FPS -s $OUTRES \
-bufsize $BUFFER -b:v $BUFF -minrate $BUFF -maxrate $BUFF -g 30 \
-c:a aac -b:a 128k -ac 2 -ar 44100 \
-f flv rtmp://$HOST/$KEY  # output to server
exit 0
# video output 768x576 854x480 1280x720
#/dev/video0 is the default v4l2 webcam ,chose correct device number
#mandatory video codec for twitch is h264 or libx264 equivalent
# codecs libx264  h264_omx h264_v4l2m2m
#bitrate 4M rtmp protocol

